module.exports = function(grunt){
    grunt.loadNpmTasks('grunt-concat');
    grunt.loadNpmTasks('grunt-contrib-copy');
    grunt.loadNpmTasks('grunt-contrib-clean');
    grunt.loadNpmTasks('grunt-contrib-concat');
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-contrib-cssmin');
    grunt.loadNpmTasks('grunt-filerev');
    grunt.loadNpmTasks('grunt-rev');
    grunt.loadNpmTasks('grunt-usemin');
    grunt.loadNpmTasks('grunt-inline-angular-templates');

    grunt.initConfig({
        copy:{
            main:{
                files:[{
                    expand:true,
                    cwd:'static/components/bootstrap/dist/fonts/',
                    src:"**/*",
                    dest:"build/fonts"
                },{'build/index.html':'static/index.html'},{
                    'build/favicon.ico':'static/favicon.ico'
                }]
            }
        },
        clean:{
            main:['build']
        },
        useminPrepare:{
            html:'static/index.html',
            options:{
                dest:'build'
            }
        },
        rev:{
            options:{
                encoding:'utf8',
                algorithm:'md5',
                length:8
            },
            assets:{
                files:[{
                    src:['build/**/*.{js,css,png}']
                }]
            }
        },
        usemin:{
            html:'build/index.html'
        },
        inline_angular_templates:{
            dist:{
                options:{
                    base:'static/',
                    prefix:'/'
                },
                files:{
                    'build/index.html':['static/pages/*.html']
                }
            }
        }
    });

    grunt.registerTask('default',
        ['clean',
            'copy',
            'useminPrepare',
            "concat",
            "uglify",
            "cssmin",
            "rev",
            "usemin",
            "inline_angular_templates"
        ]);
}